language: scala
scala:
- 2.12.2
jdk:
- oraclejdk8
script:
- travis_wait 90 sbt clean coverage test coverageReport
notifications:
  irc: irc.freenode.org#cilib
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/9df9c83ef091cee2f675
    on_success: always
    on_failure: always
    on_start: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && { travis_wait 90 sbt publish; };"
env:
  global:
  - secure: qmlLscS78OMGDv7sjWw+4MebzW5HxHZopMEhiNheF4OLDwOLjtjV3ZIUy3Vq3FhHpD2SnzO91co0i/PnNSXO0K6F6DI3UcE/y0syG8NehgxzTT0rsosHKaQdCw1MG8fiaYGvP3JUGmt8R7VYsuZNc2xPweMdrQV+/nLcmUPp7s0NnuBzMTfi9utX3lHGiiFoBm5EH7C1q2JKrxcrYOc31jVCw4iblQcnyudKlCm/R6o5C7DJ8h5fwNcn3zDtRc7wGQ/3KKD9oFXEcpEInwkjJZfZjj6Xsp4o6JhC7nbok+8+jQ1Cygud0NiVfXqA8lAcsQYtLAHnPhlB4orY+Pvre/MFsIeemOZwOkg4KGxUzrhZ0wSlBXInBW+XnRYTz9U6kh8nJLmbw5FgQo/5u6t67tB5bYFsS4HH7wDU3YvbzChcjv/jb3JXRMQkGIy/fSlIziE8YI3Z43nuJd9efQTeOMAfX8eQdvPxNNkCKTef5KDlJzLeTF2ZFK/olqSfFRfNqJTAkTaunNwcZLy03715qCwn+ja9Mto4IJVp/1PKPOgwYx5MAwOHiq8F77NYC0azASSNeEtGoGBWYtWpeTx0BpwPErgqDidHhO4bCdOcvYJPD6i1svNHwM5kHKZAB/z10QHBYnFddI3GZyDrbIJK89s0Tr31Xu3GyVib+dA9cI0=
  - secure: p00PMnxOS4IfqJ15q/pA4t/MBOpZslTGWPsigRDReMIZ3r1PcSlEQrvMg58DDik4mSG9UgSWnMEOP2etZEXVzV5GgtMqFli3shJXu2ptufy4OQoKVPSjbV2YpnJ81VClXcDAQlI+mI4PSK5URMb2RO2Rl0W4jevWMjLPkl3m0w/nc/0G3ykySbdihAvneT5KmaPIQh+Xjc1EZ5ny8jMgW3slP8q+1VZ1UaH3KpLyyJtO3SiVChe3GnC1UVf+aaxLObOk3M4GHgdMXHN1bF0nTVMi5uc5c+o/Wly0xGccUbas2Wp0eGYupHM5QYxKtDDiuad/2i/bvk/V1jZrTbSiPt891q/haYkr5oiFiwKeugz7yuv0m9AIcbHS6cZUgJiOgwbg0jdLU3ll0RNlfzGqHipt5kS/0ZRGTb95gfIoJhkSlUgM9f5rwBDZvfGHdzddaFPAUmEO/QheEwqAuxaQAU7RyB5rBYpSeHHhJzQ4EIsSE/86uyO2wyAIA2uQva35eIkxaZRFwtXeXsCp1vJmAHdv0hdEd3VUmE80FN8fqvvoVYPZa64L2Yd4WrBblge6lV0bx4LT9snkWOICrRmjNhJMtmQc5Brs9vaX6izz3ca2XZoH+RzthxH+h1SLN9WKshR2459UvcsrAbhw2pCcq+jMD9FbcSQVzN93Kq06SUw=
branches:
  only:
    - master
