name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: ['2.12.14', '2.13.6']
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12

      - run: nix-shell --run 'sbt -Dsbt.supershell=false ++${{ matrix.scala }}! test'

      - uses: codecov/codecov-action@v1
